float_server:
  msg_type: "std_msgs/Float32"
  origin: "server"
float_client:
  msg_type: "std_msgs/Float32"
  origin: "client"
string_client:
  msg_type: "std_msgs/String"
  origin: "client"
string_server:
  msg_type: "std_msgs/String"
  origin: "server"
